FROM golang:1.24 AS builder
WORKDIR /app
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o boldd cmd/api/main.go

# Final stage
FROM builder AS development
RUN go install github.com/air-verse/air@latest
CMD ["air"]