services:
  bolddapi:
    container_name: boldd
    image: bigdev/boldd:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      args:
        CONFIG_PATH: ${CONFIG_PATH:-/etc/boldd/config.yaml}
    ports:
      - 8002:8002
    networks:
      - boldd_api

networks:
  boldd_api:
    driver: bridge