services:
  bolddapi:
    container_name: boldd
    image: bigdev/boldd:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8003:8003
    networks:
      - boldd_api
    depends_on:
      - postgresdb
      - migrate:
        condition: service_completed_successfully

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ":5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - boldd_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: boldd_migrations
    volumes:
      - ./internal/infrastructure/persistence/migrations:/migrations:ro
    command: ["-path", "/migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@postgresdb:5432/${DB_NAME}?sslmode=disable", "up"]
    depends_on:
      postgresdb:
        condition: service_healthy
      networks:
        - boldd_api

networks:
  boldd_api:
    driver: bridge

volumes:
  postgres_data: {}