definitions:
  auth.AuthResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  auth.RegisterRequest:
    properties:
      email:
        type: string
      fullname:
        maxLength: 60
        minLength: 6
        type: string
      password:
        minLength: 6
        type: string
      phone_number:
        type: string
    required:
    - email
    - fullname
    - password
    - phone_number
    type: object
  auth.ResendEmailRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  auth.ResetPasswordRequest:
    properties:
      code:
        minLength: 6
        type: string
      email:
        type: string
      password:
        type: string
    required:
    - code
    - email
    - password
    type: object
  auth.VerifyEmailRequest:
    properties:
      code:
        minLength: 6
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
  categories.CreateCategoryRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  categories.UpdateCategoryRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  dtos.CategoryResponse:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  dtos.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  dtos.SubCategoryResponse:
    properties:
      category_id:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  profile.ChangePasswordRequest:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    required:
    - new_password
    - old_password
    type: object
  subcategories.CreateSubCategoryRequest:
    properties:
      category_id:
        type: string
      name:
        type: string
    required:
    - category_id
    - name
    type: object
  subcategories.UpdateSubCategoryRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
info:
  contact:
    email: dann.dev09@gmail.com
    name: Daniel Ibok
    url: https://bigdann.vercel.com
paths:
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      description: '"forgot password request"'
      parameters:
      - description: forgot password email payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.ResendEmailRequest'
      produces:
      - application/json
      responses:
        "404":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"forgot password"'
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: '"Login user"'
      parameters:
      - description: User Login details
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: body
          schema:
            $ref: '#/definitions/auth.AuthResponse'
        "400":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"authorize a user"'
      tags:
      - Auth
  /auth/refresh-token:
    post:
      consumes:
      - application/json
      description: '"Refresh user access token"'
      parameters:
      - description: User registration details
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: body
          schema:
            $ref: '#/definitions/auth.AuthResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"refresh token"'
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: '"Registers a new user"'
      parameters:
      - description: User registration details
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: body
          schema:
            $ref: '#/definitions/auth.AuthResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"register user"'
      tags:
      - Auth
  /auth/resend-confirmation-email:
    post:
      consumes:
      - application/json
      description: '"Resend confirmation email to user"'
      parameters:
      - description: resend confirmation email payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.ResendEmailRequest'
      produces:
      - application/json
      responses:
        "404":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"resend confirmation email"'
      tags:
      - Auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: '"reset password request"'
      parameters:
      - description: forgot password email payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "404":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"reset password"'
      tags:
      - Auth
  /auth/verify-email:
    post:
      consumes:
      - application/json
      description: '"Verify a user email address"'
      parameters:
      - description: verify email payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.VerifyEmailRequest'
      produces:
      - application/json
      responses:
        "400":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "404":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"verify user email"'
      tags:
      - Auth
  /categories/:
    get:
      consumes:
      - application/json
      description: '"get all product categories"'
      parameters:
      - description: page number
        in: query
        name: page
        type: integer
      - description: page data size
        in: query
        name: page_size
        type: integer
      - description: sort by
        in: query
        name: sort_by
        type: string
      - description: order
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"get all categories"'
      tags:
      - Category
    post:
      consumes:
      - application/json
      description: '"product categories"'
      parameters:
      - description: Create category payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/categories.CreateCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: "\t\t\t\"\"\t\t\t\t\t\t\t\t\t\"no response"
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"product categories"'
      tags:
      - Category
  /categories/{id}:
    delete:
      consumes:
      - application/json
      description: '"retrieve a single category from database"'
      parameters:
      - description: category id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "404":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"get a single category"'
      tags:
      - Category
    get:
      consumes:
      - application/json
      description: '"retrieve a single category from database"'
      parameters:
      - description: category id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: category
          schema:
            $ref: '#/definitions/dtos.CategoryResponse'
        "404":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"get a single category"'
      tags:
      - Category
    put:
      consumes:
      - application/json
      description: '"update a single category in the database"'
      parameters:
      - description: category id
        in: path
        name: id
        required: true
        type: string
      - description: category id
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/categories.UpdateCategoryRequest'
      produces:
      - application/json
      responses:
        "404":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"update a single category"'
      tags:
      - Category
  /profile/:
    get:
      consumes:
      - application/json
      description: '"get user profile information"'
      produces:
      - application/json
      responses:
        "403":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      security:
      - BearerAuth: []
      summary: '"get user profile"'
      tags:
      - Profile
  /profile/change-password:
    post:
      consumes:
      - application/json
      description: '"change authenticated user password"'
      parameters:
      - description: Change password payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/profile.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "400":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "403":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      security:
      - BearerAuth: []
      summary: '"change user password"'
      tags:
      - Profile
  /subcategories/:
    get:
      consumes:
      - application/json
      description: '"get all product subcategories"'
      parameters:
      - description: page number
        in: query
        name: page
        type: integer
      - description: page data size
        in: query
        name: page_size
        type: integer
      - description: sort by
        in: query
        name: sort_by
        type: string
      - description: order
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"get all subcategories"'
      tags:
      - SubCategory
    post:
      consumes:
      - application/json
      description: '"product subcategories"'
      parameters:
      - description: Create subcategory payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/subcategories.CreateSubCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: no response
          schema:
            type: "null"
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"product subcategories"'
      tags:
      - SubCategory
  /subcategories/{id}:
    delete:
      consumes:
      - application/json
      description: '"retrieve a single subcategory from database"'
      parameters:
      - description: subcategory id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "404":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"get a single subcategory"'
      tags:
      - SubCategory
    get:
      consumes:
      - application/json
      description: '"retrieve a single subcategory from database"'
      parameters:
      - description: subcategory id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: category
          schema:
            $ref: '#/definitions/dtos.SubCategoryResponse'
        "404":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"get a single subcategory"'
      tags:
      - SubCategory
    put:
      consumes:
      - application/json
      description: '"update a single subcategory in the database"'
      parameters:
      - description: category id
        in: path
        name: id
        required: true
        type: string
      - description: category id
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/subcategories.UpdateSubCategoryRequest'
      produces:
      - application/json
      responses:
        "404":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: '"update a single subcategory"'
      tags:
      - SubCategory
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
