CREATE TABLE IF NOT EXISTS subcategories (
    id SERIAL PRIMARY KEY,
    uuid TEXT NOT NULL,
    category_id INT REFERENCES categories(id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);