CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    UUID TEXT NOT NULL DEFAULT gen_random_uuid(),
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(30) NOT NULL,
    phone_number TEXT NOT NULL,
    password TEXT NOT NULL,
    referral_token VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);