application:
  port: 8002
  timezone: "hwefw"
  environment: "development"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "boldd"
  sslmode: "disabled"